### ISSUE TITLE
How to access command line params from Preprocessor

### ISSUE THREAD

**Issue by atbest** [asciidoctor/asciidoctor-extensions-lab#72]
I am planning to write a preprocessor to parse attributes from a yaml file as described in [566](https://github.com/asciidoctor/asciidoctor/issues/566). In order to maximize the use of the config file, I am planing to implement a theme feature from the config file, which contains common attributes (overidable) and theme specific attributes.
Example:
```yaml
linkcss: true
copycss: true
stylesdir: styles
themes:
   bright:
      stylesheet: asciidoctor
      source-highlighter: highlight.js
      highlightjs-theme: atom
   dark:
      stylesheet: asciidoctor-dark
      source-highlighter: highlight.js
      highlightjs-theme: monokai
```
Then the cli command is `asciidoctor --config-file=conf.yml --theme=dark -a stylesdir=new_style input.adoc`. 

The order of the attributes is `cli > theme > common`. It's easier to implement `theme > common`, but for `cli > theme`, `config-file` and `theme`, the preprocessor need to read the command params.
